# Returned from /actuator/info
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"
logging:
  level:
    root: "INFO"
